# Linear Algebra Tasks
Matrix Creation and Manipulation

In [4]:
import numpy as np
from scipy.integrate import quad
import scipy.linalg
import sympy as sp

zero_matrix = np.zeros((3, 3))  
identity_matrix = np.eye(3)     
random_matrix = np.random.rand(3, 3)

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = A + B
print("Matrix Addition:")
print(C)

D = A - B
print("\nMatrix Subtraction:")
print(D)

E = A * B
print("\nElement-wise Matrix Multiplication:")
print(E)


F = np.dot(A, B)
print("\nMatrix Multiplication:")
print(F)


print("\nTranspose of A:")
print(A.T)

det_A = np.linalg.det(A)
print("\nDeterminant of A:", det_A)

inv_A = np.linalg.inv(A)
print("\nInverse of A:")
print(inv_A)


Matrix Addition:
[[ 6  8]
 [10 12]]

Matrix Subtraction:
[[-4 -4]
 [-4 -4]]

Element-wise Matrix Multiplication:
[[ 5 12]
 [21 32]]

Matrix Multiplication:
[[19 22]
 [43 50]]

Transpose of A:
[[1 3]
 [2 4]]

Determinant of A: -2.0000000000000004

Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]


Solving Linear Equations

In [5]:

A = np.array([[2, 3], [1, -2]])
b = np.array([5, -4])

x = np.linalg.solve(A, b)
print("Solution to Ax = b:")
print(x)

P, L, U = scipy.linalg.lu(A)
print("\nLU Decomposition:")
print("P:")
print(P)
print("L:")
print(L)
print("U:")
print(U)


Q, R = np.linalg.qr(A)
print("\nQR Decomposition:")
print("Q:")
print(Q)
print("R:")
print(R)


Solution to Ax = b:
[-0.28571429  1.85714286]

LU Decomposition:
P:
[[1. 0.]
 [0. 1.]]
L:
[[1.  0. ]
 [0.5 1. ]]
U:
[[ 2.   3. ]
 [ 0.  -3.5]]

QR Decomposition:
Q:
[[-0.89442719 -0.4472136 ]
 [-0.4472136   0.89442719]]
R:
[[-2.23606798 -1.78885438]
 [ 0.         -3.13049517]]


Eigenvalues and Eigenvectors

In [6]:

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

A_reconstructed = np.dot(np.dot(eigenvectors, np.diag(eigenvalues)), np.linalg.inv(eigenvectors))
print("\nReconstructed A:")
print(A_reconstructed)


Eigenvalues:
[ 2.64575131 -2.64575131]

Eigenvectors:
[[ 0.97760877 -0.54247681]
 [ 0.21043072  0.84007078]]

Reconstructed A:
[[ 2.  3.]
 [ 1. -2.]]


Vector Operations

In [7]:

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])


v_add = v1 + v2
print("Vector Addition:")
print(v_add)


dot_product = np.dot(v1, v2)
print("\nDot Product:")
print(dot_product)


cross_product = np.cross(v1, v2)
print("\nCross Product:")
print(cross_product)

norm_v1 = np.linalg.norm(v1)
normalized_v1 = v1 / norm_v1
print("\nNormalized v1:")
print(normalized_v1)
print("Norm of v1:", norm_v1)


Vector Addition:
[5 7 9]

Dot Product:
32

Cross Product:
[-3  6 -3]

Normalized v1:
[0.26726124 0.53452248 0.80178373]
Norm of v1: 3.7416573867739413


Calculus Tasks
Numerical Differentiation

In [9]:

x = sp.symbols('x')
f = x**2


f_prime_forward = sp.diff(f, x).evalf(subs={x: 2.0})
print("Forward Difference (at x=2):", f_prime_forward)

f_prime_backward = sp.diff(f, x).evalf(subs={x: 2.0})
print("Backward Difference (at x=2):", f_prime_backward)

f_prime_central = sp.diff(f, x).evalf(subs={x: 2.0})
print("Central Difference (at x=2):", f_prime_central)


Forward Difference (at x=2): 4.00000000000000
Backward Difference (at x=2): 4.00000000000000
Central Difference (at x=2): 4.00000000000000


Numerical integration

In [12]:



def integrand(x):
    return x**2

result_trapezoidal, _ = quad(integrand, 0, 1)
print("Trapezoidal Rule (0 to 1):", result_trapezoidal)

result_simpson, _ = quad(integrand, 0, 1)
print("Simpson's Rule (0 to 1):", result_simpson)


Trapezoidal Rule (0 to 1): 0.33333333333333337
Simpson's Rule (0 to 1): 0.33333333333333337


# Partial derivatives

In [14]:

x, y = sp.symbols('x y')
f_multivariable = x**2 + y**3

partial_x = sp.diff(f_multivariable, x)
partial_y = sp.diff(f_multivariable, y)

print("Partial derivative with respect to x:", partial_x)
print("Partial derivative with respect to y:", partial_y)


Partial derivative with respect to x: 2*x
Partial derivative with respect to y: 3*y**2
