# Load the dataset

In [2]:
import pandas as pd
from sklearn.datasets import load_iris

# Task 1: Feature Selection

In [3]:
iris = load_iris()
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['target'] = iris.target


correlation_matrix = df.corr()
print("Correlation Matrix:")
print(correlation_matrix)

from sklearn.feature_selection import mutual_info_classif

X = df.drop('target', axis=1)
y = df['target']
mutual_info = mutual_info_classif(X, y)
print("\nMutual Information Scores:")
print(pd.Series(mutual_info, index=X.columns).sort_values(ascending=False))


Correlation Matrix:
                   sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.117570           0.871754   
sepal width (cm)           -0.117570          1.000000          -0.428440   
petal length (cm)           0.871754         -0.428440           1.000000   
petal width (cm)            0.817941         -0.366126           0.962865   
target                      0.782561         -0.426658           0.949035   

                   petal width (cm)    target  
sepal length (cm)          0.817941  0.782561  
sepal width (cm)          -0.366126 -0.426658  
petal length (cm)          0.962865  0.949035  
petal width (cm)           1.000000  0.956547  
target                     0.956547  1.000000  

Mutual Information Scores:
petal width (cm)     0.999659
petal length (cm)    0.999512
sepal length (cm)    0.488282
sepal width (cm)     0.286569
dtype: float64


# Task 2: Feature Transformation

In [4]:

X = iris.data

from sklearn.preprocessing import StandardScaler, MinMaxScaler
import numpy as np


scaler = StandardScaler()
X_standardized = scaler.fit_transform(X)


min_max_scaler = MinMaxScaler()
X_normalized = min_max_scaler.fit_transform(X)
X_logged = np.log(X + 1)  

print("Example of standardized data:")
print(X_standardized)


Example of standardized data:
[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+0

# Task 3: Feature Creation

In [5]:

from sklearn.datasets import fetch_openml

titanic = fetch_openml(name='titanic', version=1, as_frame=True)
df_titanic = titanic.frame


df_titanic['FamilySize'] = df_titanic['SibSp'] + df_titanic['Parch'] + 1


print("Example of dataset with new feature:")
print(df_titanic.head())


KeyError: 'SibSp'

# Task 4: Polynomial Features

In [6]:

from sklearn.datasets import load_boston

boston = load_boston()
df_boston = pd.DataFrame(data=boston.data, columns=boston.feature_names)


from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=2, include_bias=False)
df_poly = poly.fit_transform(df_boston)

poly_feature_names = poly.get_feature_names(df_boston.columns)
print("Polynomial Feature Names:")
print(poly_feature_names)


ImportError: 
`load_boston` has been removed from scikit-learn since version 1.2.

The Boston housing prices dataset has an ethical problem: as
investigated in [1], the authors of this dataset engineered a
non-invertible variable "B" assuming that racial self-segregation had a
positive impact on house prices [2]. Furthermore the goal of the
research that led to the creation of this dataset was to study the
impact of air quality but it did not give adequate demonstration of the
validity of this assumption.

The scikit-learn maintainers therefore strongly discourage the use of
this dataset unless the purpose of the code is to study and educate
about ethical issues in data science and machine learning.

In this special case, you can fetch the dataset from the original
source::

    import pandas as pd
    import numpy as np

    data_url = "http://lib.stat.cmu.edu/datasets/boston"
    raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
    data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
    target = raw_df.values[1::2, 2]

Alternative datasets include the California housing dataset and the
Ames housing dataset. You can load the datasets as follows::

    from sklearn.datasets import fetch_california_housing
    housing = fetch_california_housing()

for the California housing dataset and::

    from sklearn.datasets import fetch_openml
    housing = fetch_openml(name="house_prices", as_frame=True)

for the Ames housing dataset.

[1] M Carlisle.
"Racist data destruction?"
<https://medium.com/@docintangible/racist-data-destruction-113e3eff54a8>

[2] Harrison Jr, David, and Daniel L. Rubinfeld.
"Hedonic housing prices and the demand for clean air."
Journal of environmental economics and management 5.1 (1978): 81-102.
<https://www.researchgate.net/publication/4974606_Hedonic_housing_prices_and_the_demand_for_clean_air>


# Task 5: Handling Categorical Features

In [8]:



from sklearn.preprocessing import OneHotEncoder, LabelEncoder

df_titanic_encoded = pd.get_dummies(df_titanic, columns=['Sex'])
label_encoder = LabelEncoder()
df_titanic['Pclass_encoded'] = label_encoder.fit_transform(df_titanic['Pclass'])

print("Example of dataset with encoded categorical features:")
print(df_titanic_encoded.head())


KeyError: "None of [Index(['Sex'], dtype='object')] are in the [columns]"